### ISSUE TITLE
Logo Proposal for Starred

### ISSUE THREAD

**Issue by area55git** [sinchang/starred#1]
Hello, I wish to cooperate with **starred**, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary.

[![LOGO_PROPOSAL_FOR_STARRED.jpg](https://s18.postimg.cc/ujoamy2bd/LOGO_PROPOSAL_FOR_STARRED.jpg)](https://postimg.cc/image/me68ose2d/)

**Comment by sinchang** [comment]
Welcome PR

**Comment by area55git** [comment]
Do you accept my logo proposal?
to send you the original files by Drive.

I'm new to Github and I still do not do a PR, I'll try to do it.

**Comment by sinchang** [comment]
ok, you can send me by email.  hi@sinchang.me

Thanks bro.

**Comment by area55git** [comment]
Hello, I already sent the final artwork of the logo in various formats to your email. Enjoy them.
